### ISSUE TITLE
Relational API

### ISSUE THREAD

**Issue by ept** [automerge/automerge-classic#29]
We currently support a JSON-like data structure of nested lists and maps, but the [Redux website makes a compelling argument](http://redux.js.org/docs/recipes/reducers/NormalizingStateShape.html) that you should use a relational-like structure rather than deeply nested structures. I'm opening this issue as a place to think about how to best support a relational data model besides the JSON-like data model.

In the abstract, a relational model can of course be implemented on top of JSON. However, there are some open questions around these areas:

* How to create IDs: app developers may be tempted use use incrementing integers, which would not be safe, as multiple actors may concurrently generate the same integer. UUIDs are safe, but bulky. We already internally generate IDs, so maybe we can expose them in a way that is useful to the application.
* Foreign key integrity: for example, if a list is deleted, also delete all the cards on that list (#22). This would happen automatically in a model where the cards are nested inside the list object, but if they are separate top-level objects in a relational style, you could end up with violations of the foreign key constraint (a new card is added to a list while concurrently the entire list is deleted).

**Comment by gedw99** [comment]
@ept Very interesting. I have been thinking about this also.
The link in your comment is dead btw. Did they change their minds  ? :)

**Comment by ept** [comment]
I have started work on an implementation of relational data on Automerge, called `Automerge.Table`. I'll put up a PR when it's ready, but in the meantime I would appreciate feedback on the proposed approach.

As relational data can be represented in tabular form, it might be tempting to represent such data as a 2D array (i.e. a list containing lists, e.g. where each inner list represents a row, and the outer list is the list of rows). However, I think that is a bad choice for several reasons. Instead, I suggest the following:

A relational table is implemented as a map where the values are row objects, and the key for each value is the Automerge objectId of that object. Each row object is itself an Automerge map object, mapping column names to values. Besides the row objects, the relational table also contains a special key `columns`, whose value is a list of column names.

For example:

```js
{
  authors: {
    columns: ['surname', 'forename'],
    'a75008f9-aaa6-4a60-9125-2a1be7aaeda9': {
      surname: 'Kleppmann', forename: 'Martin'
    },
    'fabddeba-7d3d-42e9-a0f8-bbd50771e91d': {
      surname: 'Cachin', forename: 'Christian'
    },
    'ce89ab28-4b83-4eb8-a685-d6f14faf199a': {
      surname: 'Guerraoui', forename: 'Rachid'
    },
    '186b4da3-d24a-468c-b75a-5dc08190c424': {
      surname: 'Rodrigues', forename: 'Luís'
    }
  },
  publications: {
    columns: ['type', 'authors', 'title', 'publisher', 'edition', 'year'],
    '29f6cd15-61ff-460d-b7fb-39a5594f32d5': {
      type: 'book',
      authors: ['a75008f9-aaa6-4a60-9125-2a1be7aaeda9'],
      title: 'Designing Data-Intensive Applications',
      publisher: "O'Reilly Media",
      year: 2017
    },
    'a7c15b27-96f5-4eea-98ae-1801c0cbb8d7': {
      type: 'book',
      authors: [
        'fabddeba-7d3d-42e9-a0f8-bbd50771e91d',
        'ce89ab28-4b83-4eb8-a685-d6f14faf199a',
        '186b4da3-d24a-468c-b75a-5dc08190c424'
      ],
      title: 'Introduction to Reliable and Secure Distributed Programming',
      publisher: 'Springer',
      edition: 'second',
      year: 2011
    }
  }
}
```

I think this representation has several advantages:

* The list of column names is needed only when rendering the data in a tabular format; usually when code accesses rows in the table, it refers to columns by name. (For example, when searching for publications, you might match values in the "title" column, not values in the 3rd column.)
* You can add or remove columns just by changing the columns list, without having to rewrite all of the rows in the table. Rewriting rows is generally not a safe thing to do in a CRDT context, because some other user may be concurrently adding new rows to the table, and they might be using the old column list.
* Just like in a relational database, there is no inherent order of rows. You can sort them by some key, of course, but there is no ordering in the data itself. We achieve this by using a map, not a list, to contain the contents of the table.
* The data model encourages application developers to use the Automerge-generated objectId to refer to rows, rather than using an application-generated ID column. This is important, because approaches for generating IDs that make sense in a centralised database (e.g. an auto-incremented integer ID) are not suitable for a CRDT context (different users may concurrently generate the same IDs, which would then clash).

As API, I have something like this in mind:

```js
let database = Automerge.change(Automerge.init(), doc => {
  doc.authors = new Automerge.Table(['surname', 'forename'])
  doc.publications = new Automerge.Table(['type', 'authors', 'title', 'publisher', 'edition', 'year'])

  // Automerge.Table.add() inserts a new row into the database and returns its primary key
  const martin = doc.authors.add({surname: 'Kleppmann', forename: 'Martin'})

  // Adding a publication that references the above author ID
  const ddia = doc.publications.add({
    type: 'book',
    authors: [martin],
    title: 'Designing Data-Intensive Applications',
    publisher: "O'Reilly Media",
    year: 2017
  })
})

// looking up a row by primary key
database.publications.byId('29f6cd15-61ff-460d-b7fb-39a5594f32d5')

// like "SELECT * FROM publications WHERE title LIKE 'Designing%'"
database.publications.filter(pub => pub.title.startsWith('Designing'))
```

Could imagine supporting a [LINQ-style query DSL](https://github.com/mihaifm/linq) on this Automerge.Table object.

**Comment by j-f1** [comment]
How would table migrations work (i.e. adding or removing a column)?

**Comment by ept** [comment]
To add or remove a column, manipulate the list of columns. For example:

```js
database = Automerge.change(database, doc => {
  // Adding a new "url" column to the publications table
  doc.publications.columns.push('url');
})
```

That won't change any of the row objects, it just updates the metadata that says what column names to expect in the row objects. If you actually look at the "url" field of any row object, it will be null or undefined since it's not there. That mirrors the behaviour of a relational database where you can add a column whose value is NULL by default.

But you can update any of the row objects to add a value for that column, in the way you might expect:

```js
database = Automerge.change(database, doc => {
  // like "UPDATE publications SET url = '...' WHERE id = '...'
  doc.publications.byId('29f6cd15-61ff-460d-b7fb-39a5594f32d5').url = 'http://dataintensive.net/'
})
```

When deleting a column, it's sufficient to remove it from the list of columns. Some row objects will still contain a value for that column, but the value can simply be ignored.
